namespace Featurama.Maui.UI.Strings;

public sealed class FeaturamaStrings
{
    public string Title { get; init; } = "Feature Requests";
    public string FilterNew { get; init; } = "New";
    public string FilterPlanned { get; init; } = "Planned";
    public string FilterInProgress { get; init; } = "In Progress";
    public string FilterDone { get; init; } = "Done";
    public string TitlePlaceholder { get; init; } = "Feature title";
    public string DescriptionPlaceholder { get; init; } = "Describe the feature...";
    public string Submit { get; init; } = "Submit";
    public string Cancel { get; init; } = "Cancel";
    public string Edit { get; init; } = "Edit";
    public string EditRequest { get; init; } = "Edit your request";
    public string Save { get; init; } = "Save changes";
    public string Saving { get; init; } = "Saving...";
    public string Saved { get; init; } = "Changes saved.";
    public string SavedPending { get; init; } = "Changes saved. Your request is still awaiting approval.";
    public string EditOwnerOnly { get; init; } = "You can only edit your own requests.";
    public string RequestBusy { get; init; } = "Wait for the current request to finish, then save again.";
    public string EditInProgress { get; init; } = "Save or cancel the current edit before editing another request.";
    public string BadgePlanned { get; init; } = "Planned";
    public string Empty { get; init; } = "No feature requests yet";
    public string EmptyHint { get; init; } = "Be the first to suggest a feature!";
    public string Error { get; init; } = "Something went wrong";
    public string Retry { get; init; } = "Retry";
    public string Refresh { get; init; } = "Refresh";
    public string Previous { get; init; } = "Previous";
    public string Next { get; init; } = "Next";
    public string PageFormat { get; init; } = "Page {0} of {1}";
    public string Pending { get; init; } = "Awaiting approval";
    public string Submitted { get; init; } = "Request submitted.";
    public string SubmittedPending { get; init; } = "Request submitted and awaiting approval. Only you can see it in the list until it is approved.";
    public string Voted { get; init; } = "Voted";
    public string Vote { get; init; } = "Vote";
    public string RemoveVote { get; init; } = "Remove vote";
    public string EmailOptional { get; init; } = "Email (optional)";
    public string EmailRequired { get; init; } = "Email (required)";
    public string EmailHint { get; init; } = "Share your email so the project team can contact you about this request.";
    public string RequiredFields { get; init; } = "Enter a title and description.";
    public string InvalidEmail { get; init; } = "Enter a valid email address.";
    public string ConfigError { get; init; } = "Could not load submission settings. Retry before submitting.";
    public string Comments { get; init; } = "Comments";
    public string CommentPlaceholder { get; init; } = "Write a comment...";
    public string AddComment { get; init; } = "Post comment";
    public string CommentRequired { get; init; } = "Enter a comment.";
    public string NoComments { get; init; } = "No comments yet.";
    public string Anonymous { get; init; } = "Anonymous";
    public string Team { get; init; } = "Project team";
    public string ToggleCommentVote { get; init; } = "Toggle vote";
    public string Close { get; init; } = "Close";
}
